version: '3.8'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: postgres
    ports:
      - "5434:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 2s
      timeout: 5s
      retries: 5

  flask:
    build: .
    command: python -m blacklist.manage run -h 0.0.0.0
    image: blacklist
    ports:
      - "5001:5000"
    volumes:
      - ./blacklist:/code/blacklist
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.flask
    depends_on:
      - postgres
