version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - TAG="develop-$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - docker-compose -f local.yml build
      - docker-compose -f local.yml run --rm flask python -m unittest discover
      - docker image ls

  post_build:
    commands:
      - docker tag blacklist:latest $REPOSITORY_URI:$TAG
      - docker push $REPOSITORY_URI:$TAG
      - printf '[{"name":"blacklist","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
