version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - TAG="develop-$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker-compose -f local.yml build
      - docker-compose -f local.yml run --rm flask python -m unittest discover
      - docker image ls

  post_build:
    commands:
      - docker tag blacklist:latest $REPOSITORY_URI:$TAG
      - docker push $REPOSITORY_URI:$TAG
      - printf '[{"name":"blacklist","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > imagedefinitions.json
      - printf '{"imageUri":"%s"}' $REPOSITORY_URI:$TAG > imageDetail.json

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
    ImageDetailArtifact:
      files:
        - imageDetail.json